### ISSUE TITLE
Should we implement React Redux to store, update, and fetch data?

### ISSUE THREAD

**Issue by mengzhuou** [Qihuiwang3/JID-4121-LMCFilm#13]
Issue: Currently we have to Pass payment price from Cart Confirmation page to Payment to Paypal file, which is a ok solution. 

Potential Solution: React Redux is a state management tool allowing us to get stored information anywhere in the file without having to pass the state through parents to prevent Prop Drilling.

**Comment by Qihuiwang3** [comment]
We have implemented this framework during sprint 2, refer to scrum-117 for admin side and scrum-127 for students side.
