### ISSUE TITLE
(Bug) Cart and available items became empty when you checkout and go back

### ISSUE THREAD

**Issue by mengzhuou** [Qihuiwang3/JID-4121-LMCFilm#23]

**Comment by mengzhuou** [comment]
Cart and reservation items became empty instead of keeping the selected items in the cart when you checkout and go back.

<img width="950" alt="image" src="https://github.com/user-attachments/assets/08eee695-0d14-46bd-b22c-f1f73bd69c00">

**Comment by Xisheng0725** [comment]
fixed by scrum-129
