### ISSUE TITLE
(UI Bug) Noticed some bug using SelectClass page

### ISSUE THREAD

**Issue by mengzhuou** [Qihuiwang3/JID-4121-LMCFilm#39]
<img width="955" alt="image" src="https://github.com/user-attachments/assets/7284219c-ed2c-4119-9ea8-ade3e272b978">

1. Could you please fix the UI issue where there's scroll-x and scroll-y bar? You can make it "hidden"

<img width="626" alt="image" src="https://github.com/user-attachments/assets/c3c6455c-f675-4e21-a2bf-c6712baa3466">

2. Could you please fix the issue components are nested with each other?

<img width="937" alt="image" src="https://github.com/user-attachments/assets/36436c8f-bee7-4bcf-99b0-4f937c5d7499">

3. Could you add a "Back" button to navigate back to the previous page?

<img width="947" alt="image" src="https://github.com/user-attachments/assets/6d35a1c1-9c44-4079-bd39-ddc13a3f4586">

4. Student entrance page should navigate to the "http://localhost:3000/SelectClass" instead of "http://localhost:3000/Reservation"

**Comment by Qihuiwang3** [comment]
Already fix these issues in scrum-124
